const title = () => {
  return "Hanif Radityo Website";
};

const keywords = () => {
  const data: string[] = [
    "Radityo",
    "radityohanif",
    "radityohanif.com",
    "radityohanif com",
    "Hanif Website",
    "Hanif",
    "Hanif Radityo",
    "Full Stack Developer",
    "Hanif Full Stack Developer",
    "Hanif Programmer Depok",
    "Programmer Depok",
    "Depok",
    "Hanif Programmer Pondok Rajeg",
    "Programmer Pondok Rajeg",
    "Freelance Programmer",
    "Freelance Programmer Daerah Cibinong",
    "Freelance Programmer Cibinong",
    "Freelance Programmer Daerah Depok",
    "Freelance Programmer Depok",
    "Freelance Programmer Daerah Depok",
    "Freelance Programmer Depok",
    "Freelance Programmer Daerah Pondok Rajeg",
    "Freelance Programmer Pondok Rajeg",
    "Pondok Rajeg",
    "Cibinong",
    "Jawa Barat",
    "Jakarta",
    "Indonesia",
    "Laravel",
    "React",
    "Chakra UI",
    "Next.js",
    "Filament",
    "Python",
    "PHP",
    "JavaScript",
    "Nginx",
    "Ubuntu",
    "Docker",
    "Bootstrap",
    "Tailwind CSS",
    "Flask",
    "Livewire",
    "jQuery",
    "YOLO",
    "MySQL",
    "PostgreSQL",
    "Supabase",
    "Oracle SQL",
    "Express.js",
    "BigQuery",
    "Midtrans",
    "Web Development",
    "Frontend",
    "Backend",
    "Database",
    "DevOps",
    "Payment Gateway",
    "AI",
    "Computer Vision",
  ];

  return data.join(",");
};

export const useMeta = {
  title,
  keywords,
};
